apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v75jh1avb-python
  janus-idp.io/tekton: v75jh1avb-python
  backstage.io/kubernetes-id: v75jh1avb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v75jh1avb-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
